teamleadercrm/sdk-js

rollup.config.js
- add option to commonjs plugin in Rollup to handle the named export of humps.
=> [FIX] Add camelizeKeys namedExport option

package.json, src/plugins/normalize.js, test/plugins/normalize.test.js
- when you receive a single object as result (not an array of objects), the data should also be normalized with the plugin now
API result:
```js
{
data: {
id: '8799873',
user_id: '6979873',
user_info: {
first_name: 'Geoffrey',
},
}
}
```
normalize result:
```js
byId: {
'8799873': {
id: '8799873',
user_id: '6979873',
user_info: {
first_name: 'Geoffrey',
}
}
}
```
=> [ENHANCEMENT] Object normalize

README.md, package.json, src/plugins/snakeCase.js, src/utils/call.js, src/utils/createDomain.js, src/utils/createFetchParameters.js, test/plugins/snakeCase.test.js, test/utils/call.test.js, test/utils/createFetchParameters.test.js
- way to pass in plugins for request data
```js
import API from '@teamleader/api';
import { camelCase, normalize, snakeCase } from '@teamleader/api'; // exported as named exports
const { users } = API({
getAccessToken: () => 'thisisatoken', // async or sync function
plugins: { response: [camelCase], request: [snakeCase] }, // at root level
});
// own plugin
const addMeta = data => ({ ...data, meta: { size: data.length } });
const init = async () => {
// (options, plugins)
const me = await users.me(undefined, { response: [normalize, addMeta] }); // at action level
console.log(me);
};
```
- **[BREAKING CHANGE]:** changed the way plugins are passed (via plugins object with `request` and `response` key)
=> [FEATURE] request plugins

package.json, src/main.js, test/main.test.js, test/plugins/camelCase.test.js, test/plugins/normalize.test.js, test/plugins/snakeCase.test.js
- export `snakeCase` from main for easy access
```js
import { snakeCase } from '@teamleader/api';
```
- imported via main in the test (to spot if the imports are wrong)
- bumped a patch version
=> [Fix] Export snakeCase function

package.json, rollup.config.js, src/plugins/snakeCase.js
- had a weird issue with a dependency not being bundled for ES5, fixed it by removing it and using decamelizeKeys from `humps` instead (already used for `camelCase`)
=> [Fix] Dependency Uglify issue

README.md, package.json, src/utils/createFetchOptions.js, src/utils/createRequestHeaders.js, src/utils/mergeConfigurations.js, test/utils/createRequestHeaders.test.js, test/utils/mergeConfigurations.test.js
This PR adds the functionality to add a `version` option to the global or local configuration (local one has priority)
as in the README now:
* `version`: (string) specific version of the API in YYYY-MM-DD format (see the [Teamleader documentation](https://developer.teamleader.eu/#/introduction/changes-&-upgrades/upgrading-your-api-version))
`version` can also be provided at a call level, in that case it will override the global setting.
```js
import API from '@teamleader/api';
const { users } = API({
getAccessToken: () => 'thisisatoken',
version: '2018-10-30',
});
const init = async () => {
// (options, plugins)
const me = await users.me(undefined, { version: '2018-09-12' }); // version 2018-09-12 is used
};
```
=> Versioning

README.md, package.json, src/main.js, src/utils/createRequestHeaders.js, src/utils/mergeConfigurations.js, test/utils/createRequestHeaders.test.js, test/utils/mergeConfigurations.test.js
For the new auth service we want to pass no access token but still use the sdk-js wrapper (through createDomainWithActions)
- handle accessToken/getAccessToken inside of mergeConfiguration
- make accessToken/getAccessToken optional
=> [Feature] Make accessToken optional

src/plugins/normalize.js, test/plugins/normalize.test.js
This PR fixes an issue in the normalize plugin where `byId` key isn't returned when the data is empty.
```javascript
data: {};
response: {};
```
```javascript
data: {};
response: {
byId: {},
};
```
=> Fix/normalize plugin default byId

CHANGELOG.md, README.md, package.json, src/main.js, test/main.test.js
- deprecation warning for `customActions` and `createDomainWithActions`
- `additionalActions` configuration option in `API()`
By using `additionalActions` you should be able to do everything `customActions` & `createDomainWithActions` could.
I'm removing both in a future update, so update your codebase if needed
instead of doing this
```js
import { getAccessToken } from './util';
import { createDomainWithActions } from '@teamleader/api';
import { baseUrl } from './constants';
const configuration = {
getAccessToken,
baseUrl,
};
const createConfiguredDomain = (domainName, actions) =>
createDomainWithActions({
configuration,
domainName,
actions,
});
export const account = createConfiguredDomain('account', ['info']);
export const discounts = createConfiguredDomain('discounts', ['validate']); …
```
=> [FEATURE] Add additionalActions configuration

.babelrc, .browserslistrc, package.json, rollup.config.js
Before: 
- es / commonjs builds were bundled via Rollup with the dependencies included
After:
- `es` (for tree shaking) and `cjs` folder in `dist` that include the transpiled files 
- change entry points in package.json
Could we have a decent check here, cause this could potentially break stuff if I made a mistake.
=> Fix build step

CHANGELOG.md, src/utils/createRequestHeaders.js, test/utils/createRequestHeaders.test.js
Before this PR, whenever `getAccessToken()` would return `undefined` as a result, we would end up with an `Authorization Bearer undefined` as a request header.
This PR ensures that the `Authorization` header is not added if the result of `getAccessToken` is `undefined`.
The problem that I'm trying to solve here is a situation that I provide a `getAccessToken()` but it does not always have to have a result. And in that case, I want to send out that request without any `Authorization` header.
=> Undefined access token

src/plugins/merge/merge.js, test/plugins/merge.test.js
Related issue: #31 
I've looked into this merge-plugin problem a lot and came to the conclusion that if we want to keep our current implementation of "plugins", this is one of the only solutions to it. So to actually use the `merge` plugin, you need to pass the `include` param to it.
f.e.
```js
API.projects.list({ include: 'participant' }, { plugins: { response: [ merge('participant') ] } })
```
It's not the worst, but also not an ideal solution. I think we should rethink the entire `plugins` implementation in the future. Right now this merge function needs to be called before any other plugin, or it will break the path resolving and it won't be able to merge. And as we add more plugins, every plugin becomes more and more complex.
The reason we have to pass the includes twice (once in the …
=> ♻️ Include needs to be passed to create a merge plugin

CHANGELOG.md, src/utils/fetchAllRequest.js
- A bug with the fetchAll option doing the wrong requests.
`lodash.merge` mutates, to avoid this, we merge 2 sources into a new object.
=> 🐛Fix fetchAll option doing wrong requests due to mutability

CHANGELOG.md, src/utils/request.js
* The package was trying to create an array of length `-1` when the amount of requests is 0 (for empty responses) and thus erroring out.
See:
_fetchAllRequest.js_
```js
6 [...new Array(amountOfRequests - 1)]
```
=> 🐛make sure amountOfRequests is never 0, fall back to 1

CHANGELOG.md, src/main.js, test/main.test.js
- [BREAKING] The `customActions` configuration object, use `additionalActions` instead
- [BREAKING] The `createDomainWithActions` function, use `additionalActions` instead
=> Remove deprecated `customActions` configuration and `createDomainWithActions` function

src/main.ts
Exported the typescript types so they can be imported in projects.
```ts
import { LocalConfiguration } from '@teamleader/api';
const someFunction = (config: LocalConfiguration) => {
...
}
```
=> Expose typescript types

CHANGELOG.md, package.json
- Converted the codebase to TypeScript. ([@lowiebenoot](https://github.com/lowiebenoot) in [#329](https://github.com/teamleadercrm/sdk-js/pull/329))
- [BREAKING] The `additionalActions` configuration option is removed, and is replaced by a `Proxy` implementation. Any domain and action will be possible, as long as you use the `API.<domain>.<action>()` format (which is our API format anyway). Proxy is not supported by IE, so you will need to polyfill that if you need to support IE. ([@lowiebenoot](https://github.com/lowiebenoot) in [#322](https://github.com/teamleadercrm/sdk-js/pull/328))
=> [6.0.0] - 2022-08-23

CHANGELOG.md, src/__tests__/main.test.ts, src/main.ts
Before this change, if you were using and endpoint 2 times, it would call a different function 2 times. This is very annoying if you are writing tests and expecting a certain endpoint to be called.
A lot of our tests were failing because it expected an endpoint to be called, but since it's always a new function, the functions didn't get called.
Solved if by caching the created functions in an object. If the endpoint has already been called, it will return the previously created function.
Should we release this as a patch or as a minor update?
=> Cache the values that are created by the proxy

CHANGELOG.md, package.json
- Cache the values that are created by the proxy. So if you call an endpoint 2 times, it will call the same function 2 times. This makes testing easier. ([@lowiebenoot](https://github.com/lowiebenoot) in [#332](https://github.com/teamleadercrm/sdk-js/pull/332))
=> [6.0.1] - 2022-08-30

CHANGELOG.md, src/__tests__/main.test.ts, src/main.ts
It's not very useful, but it's mostly just for testing, so you can mock it. You can now mock it with jest, which actually overwrites the original function.
For example:
```
jest.spyOn(API.companies, 'info').mockReturnValue(new Promise(jest.fn()));
```
=> Allow overwriting the action endpoints.

CHANGELOG.md, package.json, src/utils/__tests__/request.test.ts, src/utils/request.ts, yarn.lock
It was not possible to use sideloading when using `fetchAll` because the `included` data was stripped.
Now it merges all `included` arrays and returns them along with the data.
=> Merge `included` when using  `fetchAll`

CHANGELOG.md, package.json, src/utils/__tests__/request.test.ts, src/utils/request.ts
- Fix crash when using `fetchAll` and first request contains less sideloaded data than subsequent requests ([@lorgan3](https://github.com/lorgan3) in [#350](https://github.com/teamleadercrm/sdk-js/pull/350))
=> Support fetchall where 2nd request contains more sideloaded subjects
